version: '3.6'

services:
  database:
    container_name: "journaldb"
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=pa
    ports:
      - 3306:3306
    networks:
      - journal
   
networks:
  journal:
    external: true