FROM node:18-alpine as builder

WORKDIR /usr/src/app
COPY front/package.json ./
COPY front/*.json ./
COPY front/src ./src/
COPY front/.angular ./.angular/
RUN npm --silent install && npm install -g @angular/cli
RUN ng build

FROM node:18-alpine

WORKDIR /usr/src/app
COPY frontprod/package.json ./
RUN npm install
COPY frontprod/index.js ./
COPY --from=builder /usr/src/app/dist/* ./dist/

EXPOSE 7857
CMD ["node", "index.js"]



